import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { pageMetadata } from "@/lib/site-metadata";

export const metadata: Metadata = pageMetadata("Privacy | Villa Cinnamoon Castle", "Privacy information for inquiries submitted through the Villa Cinnamoon Castle website.", "/privacy/");

export default function PrivacyPage() {
  return <main id="main"><PageHero breadcrumb="Privacy" eyebrow="Privacy notice" title="Your inquiry data." lede="What this reference implementation collects, why it is collected and how it is handled." /><section className="section section--paper"><div className="container container--narrow"><div className="prose"><h2>Information collected</h2><p>The inquiry form may collect your name, email address, phone or messaging number, preferred dates, guest count, preferred contact method and message.</p><h2>Purpose</h2><p>The information is used only to answer questions about Villa Cinnamoon Castle and to discuss availability, pricing or a potential stay.</p><h2>Storage and delivery</h2><p>In this packaged implementation, valid submissions are stored in a private server-side NDJSON file. A production operator may configure an approved webhook to forward the record to the host or a booking workflow.</p><h2>Analytics</h2><p>No analytics service is enabled in the packaged project. A future analytics setup must not receive full inquiry messages, email addresses, phone numbers or exact dates tied to a known person.</p><h2>Retention and rights</h2><p>The final operator must publish an approved retention period and contact route for deletion or correction requests before production launch.</p><h2>Security</h2><p>The server validates submissions, limits repeated requests and uses a hidden spam field. No online payment information is requested.</p><div className="notice">This notice is an implementation-ready draft and requires owner or legal review before public production use.</div></div></div></section></main>;
}
